### ISSUE TITLE
Cannot get /

### ISSUE THREAD

**Issue by Deathangel908** [faisalraja/vue-starter#1]
![image](https://user-images.githubusercontent.com/1336703/42330568-1c749bec-807c-11e8-996b-08646ea153c8.png)

steps to reproduce:

- npm install
- npm run build
- npm run dev

**Comment by faisalraja** [comment]
Should be under /dist/ also this is still using webpack 3. I'll be updating this to 4 which should be very similar but has a lot less configs.
